<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-08T23:05:30 GMT-08:00" name="Default suite" finished-at="2023-02-08T23:06:25 GMT-08:00" duration-ms="55797">
    <groups>
    </groups>
    <test started-at="2023-02-08T23:05:30 GMT-08:00" name="Default test" finished-at="2023-02-08T23:06:25 GMT-08:00" duration-ms="55797">
      <class name="org.example.eCommerce_tc_2">
        <test-method is-config="true" signature="ConfigureAppium()[pri:0, instance:org.example.eCommerce_tc_2@74e28667]" started-at="2023-02-08T23:05:30 GMT-08:00" name="ConfigureAppium" finished-at="2023-02-08T23:05:40 GMT-08:00" duration-ms="10068" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ConfigureAppium -->
        <test-method is-config="true" signature="preSetup()[pri:0, instance:org.example.eCommerce_tc_2@74e28667]" started-at="2023-02-08T23:05:40 GMT-08:00" name="preSetup" finished-at="2023-02-08T23:05:45 GMT-08:00" duration-ms="4910" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preSetup -->
        <test-method signature="FillForm_ErrorValidation()[pri:0, instance:org.example.eCommerce_tc_2@74e28667]" started-at="2023-02-08T23:05:45 GMT-08:00" name="FillForm_ErrorValidation" finished-at="2023-02-08T23:05:58 GMT-08:00" duration-ms="13696" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Please enter your name> but was:<Please your name>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Please enter your name> but was:<Please your name>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at org.example.eCommerce_tc_2.FillForm_ErrorValidation(eCommerce_tc_2.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FillForm_ErrorValidation -->
        <test-method is-config="true" signature="preSetup()[pri:0, instance:org.example.eCommerce_tc_2@74e28667]" started-at="2023-02-08T23:05:58 GMT-08:00" name="preSetup" finished-at="2023-02-08T23:06:03 GMT-08:00" duration-ms="4868" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preSetup -->
        <test-method signature="FillForm_PositiveFlow()[pri:0, instance:org.example.eCommerce_tc_2@74e28667]" started-at="2023-02-08T23:06:03 GMT-08:00" name="FillForm_PositiveFlow" finished-at="2023-02-08T23:06:25 GMT-08:00" duration-ms="21407" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FillForm_PositiveFlow -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.example.eCommerce_tc_2@74e28667]" started-at="2023-02-08T23:06:25 GMT-08:00" name="tearDown" finished-at="2023-02-08T23:06:25 GMT-08:00" duration-ms="806" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.example.eCommerce_tc_2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
